#<% time = Time.new.strftime("%F %H:%M") %>
---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  data_bags_path: test/fixtures/data_bags
  roles_path: test/fixtures/roles
  environments_path: test/fixtures/environments
  client_rb:
    environment: testkitchen

platforms:
  - name: ubuntu-14.04
  - name: ubuntu-12.04

suites:
  - name: test_w_percona
    driver:
      network:
        - ["private_network", {ip: "172.31.6.12"}]
    run_list:
      - role[w_common_role]
      - role[w_percona_role]
